/* Explore 2040 — content + geometry. No personal names in visible UI. */
const DISTRICTS = [
  {
    id: "mobility",
    name: "Mobility District",
    accent: "var(--cyan)",
    accentHex: "#2BE5FF",
    tagline: "Move the whole city — smarter, calmer, greener.",
    pilot: "ahmad",
    // camera focus transform (about stage center)
    focus: "translate(874px,-40px) scale(1.3)",
    ship: { homeX: 288, homeY: 900, dx: 0, dy: -380 },
    buildings: [
      {
        id: "ai-on-the-move",
        building: "Sky Transit Hub",
        title: "AI on the Move",
        line: "Smart sky-pods read the whole city at once and get everyone home faster — and safer.",
        meta: [["Focus", "Transit"], ["For", "All ages"]],
        link: "prototypes/ai-on-the-move.html",
        preview: "Transit scene",
        intro: "videos/transport-intro.mp4",
        audio: "",
        h: 300, pos: 22,
      },
      {
        id: "city-pulse",
        building: "Traffic Command Tower",
        title: "City Pulse",
        line: "A living map of 2040 that reads every street and keeps the whole city flowing and calm.",
        meta: [["Focus", "Traffic"], ["View", "Citywide"]],
        link: "prototypes/city-pulse.html",
        preview: "Traffic map",
        audio: "",
        h: 360, pos: 60,
      },
    ],
  },
  {
    id: "vitality",
    name: "Vitality District",
    accent: "var(--coral)",
    accentHex: "#FF5E8A",
    tagline: "Care, fitness and wellbeing, powered by AI.",
    pilot: "ali",
    focus: "translate(0px,-40px) scale(1.3)",
    ship: { homeX: 960, homeY: 900, dx: 0, dy: -360 },
    buildings: [
      {
        id: "dr-ali",
        building: "Care Spire",
        title: "Dr Ali",
        line: "A gentle AI companion that helps you stay healthy and feel your best, every single day.",
        meta: [["Focus", "Health"], ["For", "Families"]],
        link: "prototypes/dr-ali.html",
        preview: "Clinic scene",
        intro: "videos/health-intro.mp4",
        audio: "",
        h: 340, pos: 24,
      },
      {
        id: "peak-2040",
        building: "The Arena",
        title: "Peak 2040",
        line: "Train like a champion with a coach that learns exactly how you move and grow.",
        meta: [["Focus", "Fitness"], ["Mode", "Live coach"]],
        link: "prototypes/peak-2040.html",
        preview: "Stadium scene",
        audio: "",
        h: 300, pos: 62,
      },
    ],
  },
  {
    id: "discovery",
    name: "Discovery District",
    accent: "var(--violet)",
    accentHex: "#B14CFF",
    tagline: "Learning and play that adapts to every mind.",
    pilot: "nadim",
    focus: "translate(-874px,-40px) scale(1.3)",
    ship: { homeX: 1632, homeY: 900, dx: 0, dy: -380 },
    buildings: [
      {
        id: "school-2040",
        building: "Learning Dome",
        title: "School 2040",
        line: "A dome where every lesson quietly shapes itself around the way you learn best.",
        meta: [["Focus", "Learning"], ["For", "Students"]],
        link: "prototypes/school-2040.html",
        preview: "Classroom scene",
        intro: "videos/education-intro.mp4",
        audio: "",
        h: 320, pos: 22, dome: true,
      },
      {
        id: "play-reactor",
        building: "Holo-Arcade",
        title: "Play Reactor",
        line: "Build wild holo-games from your own ideas, then jump straight in and play.",
        meta: [["Focus", "Play"], ["Mode", "Create"]],
        link: "prototypes/play-reactor.html",
        preview: "Game scene",
        audio: "",
        h: 290, pos: 60,
      },
    ],
  },
];

const COPY = {
  eyebrow: "Wellspring · Humans and AI · 2040",
  h1: "Explore 2040",
  sub: "Tap a pilot's ship to fly to their district.",
  footerL: "A hopeful city built by young inventors",
  footerR: "Tap · explore · enter a prototype",
};

window.DISTRICTS = DISTRICTS;
window.COPY = COPY;
